# Generated by Django 4.1.7 on 2023-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foods',
            name='category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foods',
            name='merchant_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foods',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
