# Generated by Django 4.1.7 on 2023-03-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_foods_calories_alter_foods_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
